/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TUBES;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Braga
 */
public class HOME extends javax.swing.JFrame implements Pilihan {
    
    private String id;
    private String nama;
    private String tahun;
    private String harga;
    private String sql;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNama() {
        return nama;
    }

    public void setNama(String nama) {
        this.nama = nama;
    }

    public String getTahun() {
        return tahun;
    }

    public void setTahun(String tahun) {
        this.tahun = tahun;
    }

    public String getHarga() {
        return harga;
    }

    public void setHarga(String harga) {
        this.harga = harga;
    }

    public String getSql() {
        return sql;
    }

    public void setSql(String sql) {
        this.sql = sql;
    }
    

    public void clock() {
        SimpleDateFormat sdf = new SimpleDateFormat("EE, dd MMMM yyyy");
        SimpleDateFormat sd = new SimpleDateFormat("KK:mm:ss a");
        Thread clock = new Thread() {
            public void run() {
                try {
                    for (;;) {
                        Calendar cal = new GregorianCalendar();
                        jClock1.setText("Time   : " + sd.format(cal.getTime()));
                        jClock2.setText("Date   : " + sdf.format(cal.getTime()));

                        sleep(1000);

                    }
                } catch (InterruptedException ex) {
                    Logger.getLogger(HOME.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        };
        clock.start();
    }

    /**
     * Creates new form HOME
     */
    public HOME() {
        initComponents();
        clock();
        tableMobil();
        tableMotor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("tubesalpro?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTCPU").createEntityManager();
        mobilQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM Mobil m");
        mobilList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : mobilQuery.getResultList();
        motorQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT m FROM Motor m");
        motorList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : motorQuery.getResultList();
        jLabel1 = new javax.swing.JLabel();
        jWelcome = new javax.swing.JLabel();
        jClock1 = new javax.swing.JLabel();
        jClock2 = new javax.swing.JLabel();
        jLogOut = new javax.swing.JButton();
        jPesan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablemobil = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablemotor = new javax.swing.JTable();
        jtxtcaripesan2 = new javax.swing.JTextField();
        jtxtcaripesan1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("CAR & MOTORCYCLE RENTAL");

        jWelcome.setText("WELCOME");

        jClock1.setText("jLabel2");

        jClock2.setText("jLabel2");

        jLogOut.setText("Logout");
        jLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogOutActionPerformed(evt);
            }
        });

        jPesan.setText("PESAN");
        jPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesanActionPerformed(evt);
            }
        });

        jTablemobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTablemobil);

        jTablemotor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTablemotor);

        jtxtcaripesan2.setBackground(new java.awt.Color(214, 217, 223));
        jtxtcaripesan2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtcaripesan2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcaripesan2KeyReleased(evt);
            }
        });

        jtxtcaripesan1.setBackground(new java.awt.Color(214, 217, 223));
        jtxtcaripesan1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jtxtcaripesan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcaripesan1ActionPerformed(evt);
            }
        });
        jtxtcaripesan1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtcaripesan1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jWelcome)
                        .addGap(170, 170, 170)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jClock1)
                            .addComponent(jClock2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtcaripesan1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtcaripesan2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLogOut))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPesan)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jClock1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jClock2))
                    .addComponent(jWelcome)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPesan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLogOut)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtcaripesan2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtcaripesan1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogOutActionPerformed
        Login lgn = new Login();
        lgn.setVisible(true);
        lgn.pack();
        lgn.setLocationRelativeTo(null);
        lgn.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLogOutActionPerformed
    DefaultTableModel model;
    
    @Override
    public void tableMotor(){
        Object[] mobil = {"ID MOTOR", "NAMA MOTOR", "TAHUN MOTOR", "HARGA MOTOR"};
        model = new DefaultTableModel(null, mobil);
        jTablemotor.setModel(model);
        Connection conn = new OurConnection().getConnection();
        try {
            Statement st = conn.createStatement();
            sql = "SELECT * from motor order by harga_motor desc;";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                id = rs.getString(1);
                nama = rs.getString(2);
                tahun = rs.getString(3);
                harga = rs.getString(4);
                String[] data = {id, nama, tahun, harga};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(HOME.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    @Override
    public void tableMobil(){
        Object[] mobil = {"ID MOBIL", "NAMA MOBIL", "TAHUN MOBIL", "HARGA MOBIL"};
        model = new DefaultTableModel(null, mobil);
        jTablemobil.setModel(model);
        Connection conn = new OurConnection().getConnection();
        try {
            Statement st = conn.createStatement();
            sql = "select * from mobil order by harga_mobil desc;";
            ResultSet rs = st.executeQuery(sql);
            while(rs.next()){
                id = rs.getString(1);
                nama = rs.getString(2);
                tahun = rs.getString(3);
                harga = rs.getString(4);
                String[] data = {id, nama, tahun, harga};
                model.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(HOME.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void jPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesanActionPerformed
        Reservation rsv = new Reservation();
        rsv.setVisible(true);
        rsv.pack();
        rsv.setLocationRelativeTo(null);
        rsv.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_jPesanActionPerformed

    private void jtxtcaripesan2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcaripesan2KeyReleased
        DefaultTableModel table = (DefaultTableModel)jTablemotor.getModel();
        String cari = jtxtcaripesan2.getText();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<DefaultTableModel>(table);
        jTablemotor.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(cari));
    }//GEN-LAST:event_jtxtcaripesan2KeyReleased

    private void jtxtcaripesan1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtcaripesan1KeyReleased
        DefaultTableModel table = (DefaultTableModel)jTablemobil.getModel();
        String cari = jtxtcaripesan1.getText();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<DefaultTableModel>(table);
        jTablemobil.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(cari));
    }//GEN-LAST:event_jtxtcaripesan1KeyReleased

    private void jtxtcaripesan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcaripesan1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcaripesan1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HOME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HOME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JLabel jClock1;
    private javax.swing.JLabel jClock2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jLogOut;
    private javax.swing.JButton jPesan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTablemobil;
    private javax.swing.JTable jTablemotor;
    public javax.swing.JLabel jWelcome;
    private javax.swing.JTextField jtxtcaripesan1;
    private javax.swing.JTextField jtxtcaripesan2;
    private java.util.List<TUBES.Mobil> mobilList;
    private javax.persistence.Query mobilQuery;
    private java.util.List<TUBES.Motor> motorList;
    private javax.persistence.Query motorQuery;
    // End of variables declaration//GEN-END:variables

    @Override
    public void tableUser() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public void tablePemesanan() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
