/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TUBES;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.Date;
import javax.swing.JFrame;

/**
 *
 * @author Braga
 */
public class Reservation extends javax.swing.JFrame {

    private String jenis;
    private String hp;
    private String namapesan;
    private String alamat;
    private String namakendaraan;
    private String datepinjam;
    private String datekembali;
    private String lama;
    private String harga1;
    private String hargafnl;
    private String query;
    private String query1;
    private String hapus1;
    private int harga0;
    private int hargafinal;
    private int lama1;

    /**
     * Creates new form Reservation
     */
    public Reservation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtPemesan = new javax.swing.JTextField();
        jtxtNoHp = new javax.swing.JTextField();
        jtxtAlamat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jDatePinjam = new com.toedter.calendar.JDateChooser();
        jDateKembali = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jradioMobil = new javax.swing.JRadioButton();
        jradioMotor = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jtxtNamaKendaraan = new javax.swing.JTextField();
        jPesan = new javax.swing.JButton();
        jCancel = new javax.swing.JButton();
        harga2 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 255));
        jLabel1.setText("PEMESANAN");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("JENIS KENDARAAN");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("No HP");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("ALAMAT");

        jtxtPemesan.setBackground(new java.awt.Color(214, 217, 223));

        jtxtNoHp.setBackground(new java.awt.Color(214, 217, 223));

        jtxtAlamat.setBackground(new java.awt.Color(214, 217, 223));
        jtxtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtAlamatActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("TANGGAL PINJAMAN");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("TANGGAL KEMBALI");

        jDateKembali.setBackground(new java.awt.Color(214, 217, 223));
        jDateKembali.setForeground(new java.awt.Color(214, 217, 223));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("NAMA PEMESAN");

        buttonGroup1.add(jradioMobil);
        jradioMobil.setText("Mobil");
        jradioMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jradioMobilActionPerformed(evt);
            }
        });

        buttonGroup1.add(jradioMotor);
        jradioMotor.setText("Motor");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("NAMA KENDARAAN");

        jtxtNamaKendaraan.setBackground(new java.awt.Color(214, 217, 223));

        jPesan.setBackground(new java.awt.Color(47, 54, 64));
        jPesan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPesan.setForeground(new java.awt.Color(255, 255, 255));
        jPesan.setText("PESAN");
        jPesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPesanActionPerformed(evt);
            }
        });

        jCancel.setBackground(new java.awt.Color(47, 54, 64));
        jCancel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jCancel.setForeground(new java.awt.Color(255, 255, 255));
        jCancel.setText("CANCEL");
        jCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCancelActionPerformed(evt);
            }
        });

        harga2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtPemesan)
                            .addComponent(jtxtNoHp)
                            .addComponent(jtxtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDatePinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jDateKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtNamaKendaraan, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jradioMobil)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jradioMotor)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jCancel)
                                .addComponent(jPesan, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(harga2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(290, 290, 290))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jradioMobil, jradioMotor});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jDateKembali, jDatePinjam});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jradioMobil)
                    .addComponent(jradioMotor)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtNoHp, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNamaKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(harga2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPesan)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDatePinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCancel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jDateKembali, jDatePinjam});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtAlamatActionPerformed

    private void jradioMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jradioMobilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jradioMobilActionPerformed

    public void tampilBon(String namapesan, String hp, String alamat, String datepinjam, String datekembali, String namakendaraan, String lama, String jenis, String hargafnl) {
        Bon bon = new Bon();
        bon.setVisible(true);
        bon.pack();
        bon.setLocationRelativeTo(null);
        bon.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        bon.nama.setText(namapesan);
        bon.hp.setText(hp);
        bon.alamat.setText(alamat);
        bon.tanggal.setText(datepinjam);
        bon.tanggal1.setText(datekembali);
        bon.namakendaraan.setText(namakendaraan);
        bon.durasi.setText(lama);
        bon.jenis.setText(jenis);
        bon.hargaaja.setText("Rp. " + hargafnl);
        
    }

    private void jPesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPesanActionPerformed
        Random ran = new Random();
        int idpesan = ran.nextInt((9999 - 8999) + 8999);
        hp = jtxtNoHp.getText();
        namapesan = jtxtPemesan.getText();
        alamat = jtxtAlamat.getText();
        namakendaraan = jtxtNamaKendaraan.getText();

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        datepinjam = sdf.format(jDatePinjam.getDate());
        datekembali = sdf.format(jDateKembali.getDate());
        Date d1;
        Date d2;
        try {
            d1 = sdf.parse(datepinjam);
            d2 = sdf.parse(datekembali);

            long diff = (long) (d2.getTime() - d1.getTime());
            long diffDays = diff / (24 * 60 * 60 * 1000);
            lama = Long.toString(diffDays);
            if (jradioMobil.isSelected()) {
                jenis = "Mobil";
            } else {
                jenis = "Motor";
            }
            if (namapesan.equals("")) {
                JOptionPane.showMessageDialog(null, "Please fill the Name");
            } else if (namakendaraan.equals("")) {
                JOptionPane.showMessageDialog(null, "Please fill the Vehicle name");
            } else {

                Connection conn = new OurConnection().getConnection();
                try {
                    Statement st = conn.createStatement();
                    switch (jenis) {
                        case "Mobil":
                            {
                                query1 = "Select * from mobil where nama_mobil = '" + namakendaraan + "';";
                                ResultSet rs = st.executeQuery(query1);
                                lama1 = (int) diffDays;
                                if (rs.next()) {
                                    harga1 = rs.getString(4);
                                    harga0 = Integer.parseInt(harga1);
                                    hargafinal = lama1 * harga0;
                                    hargafnl = Integer.toString(hargafinal);
                                    query = "INSERT INTO `pemesanan` VALUES (" + idpesan + ",'" + namapesan + "'," + hp + ",'" + alamat + "','" + jenis + "','" + namakendaraan + "','" + datepinjam + "','" + datekembali + "'," + diffDays + "," + hargafnl + ")";
                                    st.executeUpdate(query);
                                    JOptionPane.showMessageDialog(null, "Pemesanan telah dilakukan");
                                    
                                    
                                    tampilBon(namapesan, hp, alamat, datepinjam, datekembali, namakendaraan, lama, jenis, hargafnl);
                                    
                                    this.dispose();
                                } else if (!rs.next()) {
                                    JOptionPane.showMessageDialog(null, "Mobil tidak tersedia");
                                    PreparedStatement psts;
                                    hapus1 = "DELETE FROM pemesanan WHERE nama_kendaraan = ? ;";
                                    psts = conn.prepareStatement(hapus1);
                                    psts.setString(1, namakendaraan);
                                    psts.execute();
                                    jtxtNamaKendaraan.setText(null);
                                }       break;
                            }
                        case "Motor":
                        {
                            query1 = "Select * from motor where nama_motor = '" + namakendaraan + "';";
                            ResultSet rs = st.executeQuery(query1);
                            lama1 = (int) diffDays;
                            if (rs.next()) {
                                harga1 = rs.getString(4);
                                harga0 = Integer.parseInt(harga1);
                                hargafinal = lama1 * harga0;
                                hargafnl = Integer.toString(hargafinal);
                                query = "INSERT INTO `pemesanan` VALUES (" + idpesan + ",'" + namapesan + "'," + hp + ",'" + alamat + "','" + jenis + "','" + namakendaraan + "','" + datepinjam + "','" + datekembali + "'," + diffDays + "," + hargafnl + ")";
                                st.executeUpdate(query);
                                
                                tampilBon(namapesan, hp, alamat, datepinjam, datekembali, namakendaraan, lama, jenis, hargafnl);
                                
                                this.dispose();
                            } else if (!rs.next()) {
                                JOptionPane.showMessageDialog(null, "Motor tidak tersedia");
                                PreparedStatement psts;
                                hapus1 = "DELETE FROM pemesanan WHERE nama_kendaraan = ? ;";
                                psts = conn.prepareStatement(hapus1);
                            psts.setString(1, namakendaraan);
                            psts.execute();
                            jtxtNamaKendaraan.setText(null);
                        }       break;
                            }
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(Reservation.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (HeadlessException | ParseException e) {
            Logger.getLogger(Reservation.class.getName()).log(Level.SEVERE, null, e);
        }


    }//GEN-LAST:event_jPesanActionPerformed

    private void jCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_jCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JLabel harga2;
    private javax.swing.JButton jCancel;
    private com.toedter.calendar.JDateChooser jDateKembali;
    private com.toedter.calendar.JDateChooser jDatePinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton jPesan;
    private javax.swing.JRadioButton jradioMobil;
    private javax.swing.JRadioButton jradioMotor;
    private javax.swing.JTextField jtxtAlamat;
    private javax.swing.JTextField jtxtNamaKendaraan;
    private javax.swing.JTextField jtxtNoHp;
    private javax.swing.JTextField jtxtPemesan;
    // End of variables declaration//GEN-END:variables
}
